image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache curl jq python3 py-pip
  - pip install awscli
  
stages:
  - build

build:
  stage: build
  script:
    - $(aws ecr get-login --no-include-email --region us-west-1)
    - docker build -t $AWS_ECR_URL .
    - docker push $AWS_ECR_URL
  only:
    - master
  tags:
    - docker
